version: '3.4'

services:
    medicineTrackingSystemDb:
        container_name: medicineTrackingSystemDb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"

    ps.medicaltrackingsystem.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "MedicineTrackingSystemDatabaseSettings:ConnectionString=mongodb://medicineTrackingSystemDb:27017"
        depends_on:
            - medicineTrackingSystemDb
        ports:
            - "5000:80""
        volumes:
            - ~/.aspnet/https:/https:ro
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
